### ISSUE TITLE
overlay_centroid

### ISSUE THREAD

**Issue by skouris** [scikit-maad/scikit-maad#33]
I copy & paste the first part of the example "plot_compare_auto_and_manual_rois_selection" . It seems to plot well the first 3 figures wich is 1. the original, 2. without stationary noise and 3. the colored one. But the last just doesnt, and procces finishes with exit code 0.
Also the line of code:
Sxx_db_noNoise_smooth = sound.smooth(Sxx_db_noNoise, std=0.5, 
                         display=True, savefig=None, 
                         **{'vmin':0, 'vmax':dB_max, 'extent':ext})
didnt work aswell with those parameters and i had to remove most of them to make it work!

**Comment by shaupert** [comment]
Hi,
Thanks for you comment, I'll check that and get back to you as soon as possible (I'm on a field trip till mid december.
Sylvain

**Comment by shaupert** [comment]
Hi Skouris,
I checked the code on my computer (conda + spyder) and I did not see your problem.
On Google Colab, after cloning the Git of Scikit-maad, I run the whole example and did not get any warning or errors. I only got a trouble to display the image of the spectrogram when using the function sound.smooth. This is only a display issue, the function works well. This is due to the way Google Colab or Jupyter display multiple images at the same time. 
I will try to fix it for the next release.
Was it your problem ?

Sylvain

**Comment by skouris** [comment]
Hello,
I had to study the package for a lesson i have at uni, and it was very
frustrating at first because most of the examples weren't working for me,
for reasons that dont even have to do with the code(it might've been
something i did wrong). Thankfully after long hours of study ive kinda
learn to work with it and it was awsome, to the point that im thinking of
connecting what i've learn with scikit maad, with my thesis. Thank you and
sorry for the inconvenience.
