### ISSUE TITLE
Rename the top-level package from maad to scikit_maad

### ISSUE THREAD

**Issue by Bengt** [scikit-maad/scikit-maad#71]
All the documentation, this project, the organization and the Python package refer to this package as scikit-maad. Yet, the top-level package this project provides is called maad. That is surprising and should be avoided, because the import statement is not obvious. This can also cause issues with automatic requirement derivation tools that only consider the import name and do not resolve it to a package name. For these reasons, rename the top-level Python package to scikit_maad.

**Comment by NickleDave** [comment]
I know no one asked me, but it might be worth looking at how scikit-learn handled related issues:
https://github.com/scikit-learn/scikit-learn/issues/8215  
https://github.com/scikit-learn/scikit-learn/issues/8185  

> This can also cause issues with automatic requirement derivation tools that only consider the import name and do not resolve it to a package name.

What's an example of this? Not sure I follow.  

Also a point to consider is there's probably existing code that assumes the current package name `maad`, that you'd then break. 

Tbh I'd rather type `maad` over `scikit_maad` -- there's a reason that the actual package names are `sklearn` and `skimage`, not `scikit_learn` and `scikit_image`.

An alternative to the rename would be to add a getting started snippet right at the top of your README and the [index of the docs](https://scikit-maad.github.io/) that shows
```
import maad
```
so that it's clearer to anyone that doesn't know already

**Comment by Bengt** [comment]
There are generators for the `requirements.txt` file like [pipreqs](https://github.com/bndr/pipreqs). These try to derive the required packages of a project from the imports. In these use cases, it is beneficial if the name of the package in the top-level import is the same as the python distribution on PyPI.

**Comment by juansulloa** [comment]
Hi Bengt,

Thank you for raising this concern. We are aware that aligning the top-level project name with the distributed package name is a good practice according to PEP 423. However, after careful consideration, we have chosen to keep the current top-level package name as `maad` due to potential compatibility issues, concerns with dependency management, and potential disruptions to third-party integrations.

Changing the top-level package name could introduce challenges for existing users, including those who have written scripts, documentation, and integrated the library into various tools and systems. This decision was made to prioritize a smooth user experience and minimize potential disruptions.

We understand the importance of consistency and clarity in import statements, and we are actively working to ensure that our documentation and resources clearly convey the usage of 'scikit-maad.' While the current naming convention may not align perfectly with PEP 423, we believe it strikes a balance between best practices and the practical considerations of maintaining a stable and widely adopted library.

We appreciate your understanding and ongoing support as we navigate these considerations and strive to improve the overall user experience of our library.
