### ISSUE TITLE
BUG: TypeError: pyramid_gaussian() got an unexpected keyword argument 'multichannel'

### ISSUE THREAD

**Issue by kroegern1** [scikit-maad/scikit-maad#76]
I'm running the example on this page
https://scikit-maad.github.io/_auto_examples/2_advanced/plot_unsupervised_sound_classification.html#sphx-glr-auto-examples-2-advanced-plot-unsupervised-sound-classification-py

I run this code:
![image](https://user-images.githubusercontent.com/10619094/225449262-3b4a4a8d-aec6-4305-89fc-37caace42a94.png)

and I get this error:
 
![image](https://user-images.githubusercontent.com/10619094/225449161-8ba8ed1c-490d-4d65-959b-dd31ed9fe477.png)
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[93], line 1
----> 1 df_shape, params = features.shape_features(Sxx_db, resolution='low', rois=df_rois)
      2 df_centroid = features.centroid_features(Sxx_db, df_rois)
      4 # Get median frequency and normalize

File ~\AppData\Local\miniconda3\envs\TransientClustering\lib\site-packages\maad\features\shape.py:649, in shape_features(Sxx, resolution, rois)
    644 params, kernels = filter_bank_2d_nodc(ntheta=opt_shape['ntheta'], 
    645                                       bandwidth=opt_shape['bandwidth'], 
    646                                       frequency=opt_shape['frequency'], 
    647                                       gamma=opt_shape['gamma']) 
    648 # filter spectrogram 
--> 649 im_rs = filter_multires(Sxx, kernels, npyr, rescale=True)  
    651 # If rois are provided get mean intensity for each ROI,  
    652 # else compute mean intensity for the whole spectrogram 
    653 if rois is None: 

File ~\AppData\Local\miniconda3\envs\TransientClustering\lib\site-packages\maad\features\shape.py:343, in filter_multires(Sxx, kernels, npyr, rescale)
    340     im_pyr = tuple(transform.pyramid_gaussian(Sxx, downscale=2,  
    341                                               max_layer=1, multichannel=False))  
    342 else:     
--> 343     im_pyr = tuple(transform.pyramid_gaussian(Sxx, downscale=2,  
    344                                               max_layer=npyr-1, multichannel=False))  
    346 # filter 2d array at multiple resolutions using gabor kernels 
    347 im_filt=[] 

TypeError: pyramid_gaussian() got an unexpected keyword argument 'multichannel'
```

My maad version is 1.3.12 which is the most up-to-date on the docs. However, when I check for "pyramid_gaussian" on github, there's no multichannel argument in the maad\features\shape.py on line 343.

If I have the most up-to-date version, how can I have different code than what's on the github?

![image](https://user-images.githubusercontent.com/10619094/225449361-4593c9ce-16fa-4777-b6a1-c16b17f37535.png)

**Comment by NickleDave** [comment]
Hi @kroegern1 I'm not a dev, but looks like your version was released in November as shown on the [releases page](https://github.com/scikit-maad/scikit-maad/compare/1.3.12...production). Development code on GitHub is typically ahead of releases.

It seems there have been recent changes (in the last week) to the multichannel arg in features/shape.py as shown by commits here: https://github.com/scikit-maad/scikit-maad/commit/215f96cbcdb6ab55380880f53d7ff7ccf4707771. You can see that by clicking 

My guess is the tutorial docs just need to update to match.

Aside: you'll make it easier for devs if you copy-paste tracebacks and code snippets as text in triple backticks, instead of as screenshots, and that helps make your issue show up in future searches too

**Comment by kroegern1** [comment]
Thanks @NickleDave! How do I go about getting the latest github version rather than release version?

(I added the text of the error just now, ty)

**Comment by NickleDave** [comment]
I don't find dev setup instructions in the docs but you'll basically want to:

- [ ] clone the repo (something like `git clone git@github.com:scikit-maad/scikit-maad.git`) 

and then either:
- [ ] do an editable install directly into the virtual environment you're working in (by doing `pip install -e .` in the root of the project after you clone it, with your environment already activated), or
- [ ] build a source distribution of the package locally and then install the distribution. You could do this by installing `flit` and then running `flit build` from the root of the project. 
 
I am not sure what the devs actually use to build a distribution package, so that might be easier said then done. `pip install -e` is probably easier but if you're doing some [project](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510#sec027) that relies on maad (like an ML/"AI" paper 🙂 judging from your github profile), then depending on the dev code is less than ideal for a [reproducible environment](https://the-turing-way.netlify.app/reproducible-research/renv.html) so I would politely ask the devs to release a version with the fixes ASAP

**Comment by kroegern1** [comment]
pip install -e . worked for me, thank you so much!

And thanks for the tips on reproducibility.
