### ISSUE TITLE
loading from numpy or librosa ? + feeding ROI to tf or pytorch

### ISSUE THREAD

**Issue by gg4u** [scikit-maad/scikit-maad#81]
I wish I would have known about maad before! So powerful! I just found it searching for how to extract regions of interests on.
However, I am having a limitation:

in my research I already preprocessed audio : segmented, noise removal, and spectrograms.
I have alrady spectrograms, in form of numpy vectors (obtained from librosa).

I could not find a way to load `sound.load()` a vector, instead of a wav file.
And, possibly, already specify if the spectrogram is a power spectrogram transformed to relative decibels or `power_to_db` (from librosa).

Are there these options or am i missing something ?
I would like to avoid re-processing everything.

Second question:

it would be nice an integration layer with tensorflow or pytorch, to feed the rois; hence, generalise possibility to extract regions fo interests, also for lower representation of audios.

**Comment by juansulloa** [comment]
Hi Luigi,

scikit-maad uses NumPy to work with arrays and vectors. Therefore, if you have your data as a NumPy array or if you can upload the data as a NumPy array, you can utilize any function from the package that accepts a NumPy array as an input parameter.

Since we already work with NumPy and it is straightforward to transition from NumPy arrays to tensors, we do not have plans to develop an integration layer with TensorFlow or PyTorch.
https://pytorch.org/docs/stable/generated/torch.from_numpy.html

I'm not sure if this answers your questions. If not, please provide further information regarding your questions.

**Comment by gg4u** [comment]
Hi Juan!
thanks for following up:

on https://scikit-maad.github.io/sound.html
there is list of command for importing audio:
`sound.load()` but that loads it from filename.

What I meant it that I want to load a numpy vector that had already processed.

something like

`sound.load( y = # numpy, rate=# sample rate)`

but it only would work for files:
`TypeError: expected str, bytes or os.PathLike object, not ndarray`

**Comment by juansulloa** [comment]
Hi Luigi!

While the idea is intriguing, we find that incorporating such functionality may be unnecessary. Loading a NumPy array using the `numpy.load` function and subsequently processing the audio with scikit-maad as a NumPy array is entirely feasible. Since scikit-maad is built on top of NumPy, this approach is quite practical. In the case of using tensors, one could easily convert the tensor to a NumPy array and then utilize scikit-maad.

Considering that similar functionality is already available in other functions within base packages, we see little necessity in modifying the existing `maad.sound.load` function in scikit-maad.

Thank you for the feedback.
