### ISSUE TITLE
BUG: AttributeError: module 'scipy.signal' has no attribute 'gaussian'

### ISSUE THREAD

**Issue by jokot025** [scikit-maad/scikit-maad#94]
When running the example code for unsupervised sound classification I got the error from the title (AttributeError: module 'scipy.signal' has no attribute 'gaussian'). This confused me as I found documentation for the attribute and how to use it. 

I had replaced the existing line of code ```selem = signal.gaussian(gauss_win, gauss_std)``` in spectral_subtraction.py with ```selem = signal.windows.gaussian(gauss_win, gauss_std)``` and it seems to have resolved the issue.   

** To reproduce**
1. run plot_unsupervised_sound_classification.py
2. get AttributeError: module 'scipy.signal' has no attribute 'gaussian'

**Desktop (please complete the following information):**
    OS: Linux Mint 22.
    Spyder 3.12
    maad version 1.4.2

**Comment by shaupert** [comment]
Hi, thanks to point out the bug. I've just fixed it. It should work now for scipy >= 1.12.0

**Comment by juansulloa** [comment]
Thanks for reporting this issue. These reports help us keep scikit-maad up to date with the latest releases of its dependencies!

As Sylvain commented, this bug is related to incompatibility with the newest versions of scipy (>=1.12.0).
We have fixed this in the development version, which you can use by cloning the [production branch](https://github.com/scikit-maad/scikit-maad/tree/production) of the repository. Alternatively, you can use an older version of scipy, or just wait for the new release of scikit-maad on PyPi.

**Comment by juansulloa** [comment]
We have recently made a new release and updated the package in PyPi v1.4.3 with this bug fixed.
Please update scikit-maad and test again.
